Creation of Numpy Arrays from list

In [2]:
import numpy as np
#array from list
arr1 = np.array([1,2,5,8,9,11])
print(arr1)


[ 1  2  5  8  9 11]


In [3]:
type(arr1)

numpy.ndarray

2d array

In [7]:
arr2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(arr2)

numpy.ndarray

In [14]:
arr3 = np.array([[[1,2],
                  [3,4]],

                   [[5,6],
                    [7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
arr3.ndim

3

In [17]:
arr3.size

8

In [16]:
arr3.shape

(2, 2, 2)

In [10]:
arr1.ndim

1

In [11]:
arr2.ndim #it tells how many dimensions of array we contain

2

In [12]:
arr1.shape #it indicates how many elements of array we have

(6,)

In [13]:
arr2.shape

(3, 3)

In [19]:
arr1.dtype #To check data type of array 1

dtype('int64')

In [20]:
#the size in bytes of each element in the array
arr1.itemsize

8

In [22]:
arr1[::2]

array([1, 5, 9])

Slicing
start_index = 0
end_index = n
step_size = 1

In case you are working in your local enviroment

In [ ]:
#pip install numpy

In [23]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
subarray = arr2[0:2 , 0:2]
print(subarray)

[[1 2]
 [4 5]]


In [25]:
arr2[:, 1:] # : this means consider all the rows # take all rows but start with column one

array([[2, 3],
       [5, 6],
       [8, 9]])

In [26]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
arr3[0:2 , 1, 0:2]

array([[3, 4],
       [7, 8]])

Understanding operations on arrays

Arithmetic Operations

In [4]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

#element wise operations
c = a + b
print(c)

d = b-a
print(d)

e = a*b
print(e)

f = b/a
print(f)

g = b%a
print(g)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[0 1 0]


Transpose(convert rows into column or column into rows)

In [8]:
arr2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

sort

In [10]:
arr5 = np.array([3,1,5,2,4])
sort_arr5 = np.sort(arr5)
print(sort_arr5)


[1 2 3 4 5]


In [11]:
arr6 = np.array([[3,2,1],
                [6,5,4]])
#by default sorting is done row wise
sorted_arr6 = np.sort(arr6)
sorted_arr6


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# sorting is done column-wise
sorted_arr6 = np.sort(arr6, axis = 0)
sorted_arr6

array([[3, 2, 1],
       [6, 5, 4]])