In [1]:
import numpy as np

In [5]:
a = np.zeros(5) # all elements empty in array

In [6]:
a.ndim

1

In [7]:
a

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros(10 , dtype=float) #converts into float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(5 , dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
#2 dimension zeores error
b = np.zeros((3 , 4))

In [13]:
b.ndim

2

In [14]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones(5 , dtype=int)

array([1, 1, 1, 1, 1])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.twos(4)#doesent exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [22]:
np.array([[2,2,2,2] , [2,2,2,2]])

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [24]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
#3d arrays
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.zeros((3,4)) #3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
arr3 = np.zeros((1, 3, 4)) # 3 rows 4 columns  # 1 means 3 dimension

In [30]:
arr3.ndim

3

In [31]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
np.zeros((1,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
b = np.zeros((1, 1,3, 3))


In [36]:
b

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [38]:
b.ndim

4

In [39]:
b = np.zeros((1,1, 1,3, 3))

In [40]:
b.ndim

5

In [41]:
b

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [44]:
a = b+5 #adding 5 in b arrays

In [45]:
a

array([[[[[5., 5., 5.],
          [5., 5., 5.],
          [5., 5., 5.]]]]])

In [46]:
#multiplying every element in array by a given no
a*2

array([[[[[10., 10., 10.],
          [10., 10., 10.],
          [10., 10., 10.]]]]])

In [47]:
a

array([[[[[5., 5., 5.],
          [5., 5., 5.],
          [5., 5., 5.]]]]])

In [48]:
#subtracting every elemnet in array by 1
a-1

array([[[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]]])

In [51]:
np.eye(3) # it gives a 3 x 3 matrix with all diagnoal elements 1 and rest 0 #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
np.empty((3,4)) #returns a new array of given shape , without initializing entries,\
#it means entries in the array can be anything random values

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [57]:
#optional >> random module gives random values
import random
random.choice((1,2,3,4,5))

2

In [59]:
random.choice("Ajay")

'y'

In [60]:
random.randrange(1,10)

4

In [62]:
random.random() # a random no generated between 0(included) and 1 (excluded)

0.28436577664904295

In [63]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [67]:
random.shuffle(lis)

In [68]:
lis

[1, 4, 5, 3, 2]

In [69]:
random.uniform(7,14)
#uniform distribution - A uniform distribution is a type of probability distribution where every possible outcome has an equal chance of occurring.

11.891626775029746

In [72]:
#random numbers related concept in numpy

np.array([])

array([], dtype=float64)

In [74]:
np.random.random_sample((5, )) #1 dimension array of 5 random numbers

array([0.33505985, 0.10953782, 0.70597449, 0.06187334, 0.6015964 ])

In [75]:
np.random.rand(1)

array([0.63214285])

In [76]:
np.random.rand(2,3)

array([[0.65533752, 0.92846412, 0.11218647],
       [0.45157312, 0.39883685, 0.19989559]])

In [78]:
np.random.randn()

-0.9788441702929901

In [79]:
np.random.randint(1, 5, size = (3,4)) #it creates integer from random no bteween 1 and 5 and of sixe 3 column and 4 rows

array([[4, 2, 1, 2],
       [3, 2, 1, 4],
       [2, 3, 4, 4]])

In [80]:
arr = np.random.randint(1,5, size = (3,4))


In [81]:
arr.ndim

2

In [82]:
arr.shape

(3, 4)

In [83]:
arr

array([[1, 1, 2, 2],
       [2, 3, 2, 2],
       [2, 2, 4, 1]])

In [85]:
#reshapping of array
arr1 = arr.reshape(2,6) #returns the array containing the same data with a new shape


In [86]:
arr1

array([[1, 1, 2, 2, 2, 3],
       [2, 2, 2, 2, 4, 1]])

In [87]:
arr1.size

12

In [88]:
arr1.shape

(2, 6)

In [89]:
arr1.ndim

2

In [ ]:
#array size will never change , always reshape parameter should be multiplication  of original array size

In [90]:
arr

array([[1, 1, 2, 2],
       [2, 3, 2, 2],
       [2, 2, 4, 1]])

In [91]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [93]:
arr.reshape(3,4)

array([[1, 1, 2, 2],
       [2, 3, 2, 2],
       [2, 2, 4, 1]])

In [94]:
#case when you dont know in reshape what should be the ro or column count
#use any negative values for rows or columns
arr.reshape(4,-1)

array([[1, 1, 2],
       [2, 2, 3],
       [2, 2, 2],
       [2, 4, 1]])

In [95]:
arr.reshape(4,-100)

array([[1, 1, 2],
       [2, 2, 3],
       [2, 2, 2],
       [2, 4, 1]])

In [96]:
arr.reshape(-1,4)

array([[1, 1, 2, 2],
       [2, 3, 2, 2],
       [2, 2, 4, 1]])

In [98]:
arr.reshape(12,1)

array([[1],
       [1],
       [2],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [2],
       [4],
       [1]])

In [ ]:
arr.reshape(12,1).base #gives back the original array by adding .base

In [99]:
arr

array([[1, 1, 2, 2],
       [2, 3, 2, 2],
       [2, 2, 4, 1]])

In [100]:
#reshapping array dimension also
arr.reshape(2, 2, 3) #multiplication should be equal to arr size

array([[[1, 1, 2],
        [2, 2, 3]],

       [[2, 2, 2],
        [2, 4, 1]]])

In [104]:
arr.reshape(1,2,2,3).ndim

4

In [105]:
arr.reshape(4,3,1)

array([[[1],
        [1],
        [2]],

       [[2],
        [2],
        [3]],

       [[2],
        [2],
        [2]],

       [[2],
        [4],
        [1]]])

In [106]:
#conditions on array
arr1 = np.random.randint(1,10,(5,6))

In [107]:
arr1

array([[5, 1, 9, 4, 8, 4],
       [1, 7, 9, 7, 6, 5],
       [2, 8, 9, 1, 2, 6],
       [5, 7, 5, 3, 8, 7],
       [8, 3, 4, 1, 3, 1]])

In [108]:
arr1.shape

(5, 6)

In [109]:
arr1.ndim

2

In [110]:
arr1

array([[5, 1, 9, 4, 8, 4],
       [1, 7, 9, 7, 6, 5],
       [2, 8, 9, 1, 2, 6],
       [5, 7, 5, 3, 8, 7],
       [8, 3, 4, 1, 3, 1]])

In [111]:
arr1 > 3

array([[ True, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True,  True],
       [False,  True,  True, False, False,  True],
       [ True,  True,  True, False,  True,  True],
       [ True, False,  True, False, False, False]])

In [112]:
arr1[arr1>3] #select all elements o arr1 where the condition is true


array([5, 9, 4, 8, 4, 7, 9, 7, 6, 5, 8, 9, 6, 5, 7, 5, 8, 7, 8, 4])

In [113]:
arr1[arr1 < 3]

array([1, 1, 2, 1, 2, 1, 1])

In [114]:
#to access element in an array
arr1[0]

array([5, 1, 9, 4, 8, 4])

In [115]:
arr1[1]

array([1, 7, 9, 7, 6, 5])

In [116]:
arr1[1][2]

np.int64(9)

In [117]:
arr1[3][2]

np.int64(5)

In [118]:
arr1

array([[5, 1, 9, 4, 8, 4],
       [1, 7, 9, 7, 6, 5],
       [2, 8, 9, 1, 2, 6],
       [5, 7, 5, 3, 8, 7],
       [8, 3, 4, 1, 3, 1]])

In [119]:
#from 0th row to 2nd row
arr1[0:3]

array([[5, 1, 9, 4, 8, 4],
       [1, 7, 9, 7, 6, 5],
       [2, 8, 9, 1, 2, 6]])

In [120]:
#0 to 2nd row  and 0th and 3rd column
arr1[0:3, [0,2]]

array([[5, 9],
       [1, 9],
       [2, 9]])

In [121]:
#slicing on both rows and column together
arr1

array([[5, 1, 9, 4, 8, 4],
       [1, 7, 9, 7, 6, 5],
       [2, 8, 9, 1, 2, 6],
       [5, 7, 5, 3, 8, 7],
       [8, 3, 4, 1, 3, 1]])

In [122]:
arr1[0:3 , 1:4]

array([[1, 9],
       [7, 9],
       [8, 9]])

In [123]:
arr1[0, [1, 3]]

array([1, 4])

In [124]:
arr1[2:5]

array([[2, 8, 9, 1, 2, 6],
       [5, 7, 5, 3, 8, 7],
       [8, 3, 4, 1, 3, 1]])

In [126]:
arr1[2:5, 0:2]

array([[2, 8],
       [5, 7],
       [8, 3]])

In [128]:
#mathematical expression of 2 arrays
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [129]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [130]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [131]:
arr1+arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [132]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [133]:
arr1*arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [134]:
arr1, arr1

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]))

In [ ]:
#Matrix multiplication  >> matrix is specalized 2 -d array
#Matrix multiplication is different from index wise multiplication


In [135]:
arr1 @ arr2 # matrix multiplication

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [136]:
arr1 * arr2 #index wise multiplication

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [137]:
np.dot(arr1 , arr2) #another way of matrix multiplication

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

#BROAD CASTING

In [138]:
arr =  np.zeros((3,4))

In [139]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [141]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [142]:
a = np.array([1,2,3,4])

In [143]:
a

array([1, 2, 3, 4])

In [144]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [145]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
#transpose >> converting rows to columns and columns to rows


In [ ]:
a = np.array([[1,2,3,4]])

In [158]:
a

array([1, 2, 3, 4])

In [159]:
a.T

array([1, 2, 3, 4])

In [155]:
arr2 = np.array([[2,3,4], [5,6,7]])

In [156]:
arr2

array([[2, 3, 4],
       [5, 6, 7]])

In [157]:
arr2.T

array([[2, 5],
       [3, 6],
       [4, 7]])