Creation of Numpy Arrays from list

In [1]:
import numpy as np
#array from list
arr1 = np.array([1,2,5,8,9,11])
print(arr1)


[ 1  2  5  8  9 11]


In [ ]:
type(arr1)

numpy.ndarray

2d array

In [3]:
arr2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
arr3 = np.array([[[1,2],
                  [3,4]],

                   [[5,6],
                    [7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr3.size

8

In [ ]:
arr3.shape

(2, 2, 2)

In [ ]:
arr1.ndim

1

In [4]:
arr2.ndim #it tells how many dimensions of array we contain

2

In [5]:
arr1.shape #it indicates how many elements of array we have

(6,)

In [ ]:
arr2.shape

(3, 3)

In [6]:
arr1.dtype #To check data type of array 1

dtype('int64')

In [ ]:
#the size in bytes of each element in the array
arr1.itemsize

8

In [ ]:
arr1[::2]

array([1, 5, 9])

Slicing
start_index = 0
end_index = n
step_size = 1

In case you are working in your local enviroment

In [ ]:
#pip install numpy

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
subarray = arr2[0:2 , 0:2]
print(subarray)

[[1 2]
 [4 5]]


In [10]:
arr2[:, 1:] # : this means consider all the rows # take all rows but start with column one

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr3[0:2 , 1, 0:2]

array([[3, 4],
       [7, 8]])

Understanding operations on arrays

Arithmetic Operations

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

#element wise operations
c = a + b
print(c)

d = b-a
print(d)

e = a*b
print(e)

f = b/a
print(f)

g = b%a
print(g)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[0 1 0]


Transpose(convert rows into column or column into rows)

In [ ]:
arr2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

sort

In [ ]:
arr5 = np.array([3,1,5,2,4])
sort_arr5 = np.sort(arr5)
print(sort_arr5)


[1 2 3 4 5]


In [ ]:
arr6 = np.array([[3,2,1],
                [6,5,4]])
#by default sorting is done row wise
sorted_arr6 = np.sort(arr6)
sorted_arr6


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# sorting is done column-wise
sorted_arr6 = np.sort(arr6, axis = 0)
sorted_arr6

NameError: name 'arr6' is not defined

Get the indices that would sort the array

In [ ]:
sorted_indices = np.argsort(arr5)
print(sorted_indices)

NameError: name 'np' is not defined

Concatenating Arrays

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate joins the arrays end-to-end
result = np.concatenate((arr1, arr2))

print(result)
# Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]


Reshaping Arrays # use to convert 1 d array into 2d

In [ ]:
import numpy as np

arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

# Fix: Match the variable name (lowercase 'd')
arr_2d = arr_1d.reshape(4, 3)


print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
arr_3D = arr_1d.reshape(2, 2, 3)
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Flattend array

In [ ]:
#converting the higher dimension array to 1D
import numpy as np

# Assuming arr_2d was defined in your previous step
# Fix: Use lowercase 'd' to match your variable name
flattened = arr_2d.reshape(-1)

print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


Splitting array