In [12]:
import numpy as np
l = [1, 2, 3, 4, 5] # Use square brackets to make a list
arr = np.array(l)         # Use parentheses to call the function

In [13]:
type(arr)

numpy.ndarray

In [16]:
l = [1, 2, 3, 4, 5, "Ajay"]
np.array(l)

array(['1', '2', '3', '4', '5', 'Ajay'], dtype='<U21')

In [ ]:
#array stores homogeneous data

In [20]:
l = [1, 2, 3, 4, 5, 2.5]
np.array(l)


array([1. , 2. , 3. , 4. , 5. , 2.5])

In [21]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [22]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr1.ndim

2

In [25]:
mat = np.matrix([1,2,3,4]) #matrix is a specalized array of 2 dimension


In [26]:
type(mat)

numpy.matrix

In [28]:
mat.ndim

2

In [ ]:
#To understand the dimension , see the no of opening / closing square  bracket

In [30]:
np.matrix([[[1,2],[3,4]]]) # will throw error because matrix can be of 2 dimensio

ValueError: matrix must be 2-dimensional

In [33]:
l = [1,2,3]
np.asarray(l) # initial function was to convert an array , np.array come after this

array([1, 2, 3])

In [34]:
np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [ ]:
#asanyarray will convert the input to an ndarray , but if something is already in array

In [35]:
mat

matrix([[1, 2, 3, 4]])

In [36]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

#convert tuple into array

In [37]:
t = ([1,2,3], [4,5,6])
type(t)

tuple

In [38]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr

array([1. , 2. , 3. , 4. , 5. , 2.5])

#accessing the element of arrray

In [42]:
arr[0]

np.float64(1.0)

In [43]:
#array is mutable
arr[0] = 1000

In [44]:
arr

array([1000. ,    2. ,    3. ,    4. ,    5. ,    2.5])

In [45]:
# a and arr will point to same memory location , so there is change is a  as arr
#it will reflect on both
a = arr

In [46]:
a

array([1000. ,    2. ,    3. ,    4. ,    5. ,    2.5])

In [47]:
arr

array([1000. ,    2. ,    3. ,    4. ,    5. ,    2.5])

In [48]:
#shallow copy>> change in one array will led to change in another


In [49]:
a

array([1000. ,    2. ,    3. ,    4. ,    5. ,    2.5])

In [50]:
arr

array([1000. ,    2. ,    3. ,    4. ,    5. ,    2.5])

In [51]:
b = arr.copy()

In [52]:
b

array([1000. ,    2. ,    3. ,    4. ,    5. ,    2.5])

In [53]:
b[0] = 11000

In [56]:
arr #change in one array will not reflect in another

array([1000. ,    2. ,    3. ,    4. ,    5. ,    2.5])

In [62]:
np.fromfunction(lambda i , j: i==j,(3,3)) #construct an array by executing a function over each coordinate:

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [63]:
arr1.ndim

2

In [67]:
arr1.shape #shape of array

(2, 3)

In [68]:
arr1.size #no of elements in array

6

In [70]:
arr2 = np.fromfunction(lambda i, j: i*j, (3,3))

In [71]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [72]:
arr2.ndim

2

In [73]:
arr2.shape

(3, 3)

In [74]:
arr2.size

9

In [75]:
for i in range(5):
  print(i)

0
1
2
3
4


In [76]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [78]:
#another method of numpy >> to generate sequence of number
np.arange(1,10) # arange returns evenly specified values within a given interval

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.linespace(1,5 , 10) # give me 10 number between 1 and 5

AttributeError: module 'numpy' has no attribute 'linespace'