In [3]:
import numpy as np

In [4]:
arr1 = np.random.randint(1, 3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [5]:
arr1

array([[2, 2, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [6]:
arr2

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [7]:
arr1.flatten()

array([2, 2, 2, 1, 1, 2, 1, 1, 1])

In [8]:
#expand dimension
arr = np.array([1,2,3,4])

In [9]:
arr

array([1, 2, 3, 4])

In [12]:
arr.ndim

1

In [14]:
np.expand_dims(arr, axis=0) #increase the dimension by 1 in the provided axis

array([[1, 2, 3, 4]])

In [15]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [17]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
np.expand_dims(arr, axis = 0).ndim

3

In [21]:
np.expand_dims(arr, axis = 1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [22]:
a = np.array([[1] , [2], [3]])

In [23]:
a

array([[1],
       [2],
       [3]])

In [24]:
a.ndim

2

In [25]:
#convert 2d array to 3d #squzeeing the dimension
np.squeeze(a)

array([1, 2, 3])

In [26]:
a

array([[1],
       [2],
       [3]])

In [28]:
np.repeat(3,4)

array([3, 3, 3, 3])